import Nav from "@/components/Nav";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";

export const metadata = {
  title: "Task Master",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       {/* <Nav>{ children }</Nav> */}
       <UserProvider>
       {children}
       </UserProvider>
      </body>
    </html>
  );
}
